### ISSUE TITLE
+1

### ISSUE THREAD

**Issue by sirthias** [ktoso/sbt-jol#1]
:)

**Comment by ktoso** [comment]
:)

**Comment by ktoso** [comment]
:)

**Comment by ktoso** [comment]
Now available as `"pl.project13.sbt" % "sbt-jol" % "0.1"`

 [ ![Download](https://api.bintray.com/packages/ktosopl/sbt-plugins/sbt-jol/images/download.svg) ](https://bintray.com/ktosopl/sbt-plugins/sbt-jol/_latestVersion)

**Comment by sirthias** [comment]
Excellent! Thank you a lot!
